In [1]:
import numpy as np

In [9]:
x=np.array([[1,2],[3,4]])
print("Matrix A:")
print(x)
y=np.array([[5,6],[7,8]])
print("\n Matrix B:")
print(y)
z=x+y
print("\n Matrix A+B:")
print(z)

Matrix A:
[[1 2]
 [3 4]]

 Matrix B:
[[5 6]
 [7 8]]

 Matrix A+B:
[[ 6  8]
 [10 12]]
