In [76]:
#To import numpy
import numpy as np

In [15]:
#To make 0D array
a=np.array([31])
print(a)

[31]


In [6]:
#To make a 1D array
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [8]:
#To make 2D array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [28]:
#To make 3D array
arr2=np.array([[[1,2],[3,4],[5,6]]])
print(arr2)
print(arr2.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
3


In [17]:
#To check number of dimension 
print(arr1,"is a",arr1.ndim,"dimensional array")

[[1 2 3]
 [4 5 6]] is a 2 dimensional array


In [25]:
#To define number of dimensions
b=np.array([1,2,3,4,5],ndmin=2)
print(b)
print(b.ndim)

[[1 2 3 4 5]]
2


In [30]:
#To print specific index
c=np.array([1,2,3,4,5])
arr2=np.array([[[1,2],[3,4],[5,6]]])
arr1=np.array([[1,2,3],[4,5,6]])
print(c)
print(c[2])
print(c[-2])
print(arr2[0,2,1])
print(arr1[0,2])

[1 2 3 4 5]
3
4
6
3


In [31]:
#Slicing and step slicing
c=np.array([1,2,3,4,5])
print(c[1:3]) #Slicing
print(c[1::2]) #Step slicing

[2 3]
[2 4]


In [39]:
#Slicing in multi-dimensonal array
arr1=np.array([[1,2,3,4,5,6,9],[3,7,9,0,4,5,6]])
print(arr1[0:3,0:4])

[[1 2 3 4]
 [3 7 9 0]]


In [40]:
#To copy an array
c=np.array([1,2,3,4,5])
x=c.copy()
c[2]=9
print(c)
print(x)
#Copying does not induce the change of original array

[1 2 9 4 5]
[1 2 3 4 5]


In [42]:
#To view an array
c1=np.array([1,2,3,4,5])
x1=c1.view()
print(x1)
c1[2]=9
print(c1)
print(x1)
#Viewing changes the array if original is changed

[1 2 3 4 5]
[1 2 9 4 5]
[1 2 9 4 5]


In [43]:
#To check if array owns its data or not using base feature
arr4 = np.array([1, 2, 3, 4, 5])
z = arr4.copy()
y = arr4.view()
print(x.base)
print(y.base)
#if O/P ---> None , array owns the data,copy owns the data
#if O/P ---> array , it doesnt own the data,view doesnt own the data

None
[1 2 3 4 5]


In [46]:
#To print shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(arr)
# O/P is (x,y) then , for a rough idea ,x is dimension and 4 is elements in a row 

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [57]:
#To reshape an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
narr = arr.reshape(4, 3)#it tells to make the array 'arr' 4D and each row with 3 elements
print(narr)
print()
karr=arr.reshape(3,2,2)#make 3 2D arrays with 2 elements in each row
print(karr)
print()
carr=narr.reshape(-1)#to reset the array
print(carr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [61]:
#To join two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [70]:
#To join two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)#makes a matrix after joining
arrc = np.vstack((arr1, arr2))#vertical stack
arrk = np.hstack((arr1, arr2))#horizontal stack
print("vertical" ,arrc)
print("horizontal \n", arrk)
print("normal \n",arr)

vertical [[1 2 3]
 [4 5 6]]
horizontal 
 [1 2 3 4 5 6]
normal 
 [[1 4]
 [2 5]
 [3 6]]


In [71]:
#To split the array
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)#Split in 3 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [72]:
#To locate an item
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)#Gives index value where 4 is
print(x)

(array([3, 5, 6]),)


In [74]:
#Searchsorted
a=np.array([1,2,3,4,6,7,8])
x=np.searchsorted(a,5)#Finds location where item should be inserted to make the array sorted
print(x)

4


In [75]:
#To sort an array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]
